### ISSUE TITLE
Partition used space reads 0 bytes used

### ISSUE THREAD

**Issue by ghost** [sondree/b2_fuse#14]
Hello!
Awesome project here that I like, able to mount as a filesystem with ease.

However, a quick look at `df -h` in my server shows an issue of the used disk space reads a constant 0 bytes, while over on my buckets page shows a true value.

> Filesystem      Size  Used Avail Use% Mounted on
> B2Fuse---- 64P     0---- 64P---   0% /var/nfs/backblaze-s3

**Comment by falense** [comment]
This should not be too difficult to add. I'll to to get this into the 1.3 release with the new backend.

**Comment by falense** [comment]
This was added in 1.3 and b2_fuse now correctly reports used disk space in bucket. 

Best
