### ISSUE TITLE
mount folder not accessible after starting b2fuse.py for "Online only copy"

### ISSUE THREAD

**Issue by mattrummler** [sondree/b2_fuse#15]
It's not feasible for me to utilize b2_fuse in the "With local copy" mode, (which works fine).
Therefore I have been attempting to utilize b2fuse.py as described in the documentation.
It runs (and gives me the status, repeated over time).
Unfortunately nothing can read from or write to the folder.
In fact the folder shows exactly the symptoms described in this Stack Exchange question: http://superuser.com/questions/169977/mount-point-permission-denied
Unfortunately what that user did to fix the problem does not directly translate.
I have set fuse.conf to allow_root and user_allow_other with no change (including after restarting the server and also waiting for an extended amount of time... hours...).

I have never utilized fuse before this so it could still be some configuration error on my part... if it is I apologize.

I started looking into the code and attempting to figure out if there was something that needed to be passed to libfuse that was missed (by looking @ the fuse api, then looking through the libfuse code then the b2fuse code)... I am not very proficient with python & decided to go a different direction (instead of attempting to get b2 mounted locally).

MORE DETAILS:
OS=Ubuntu 14.04.5 server (64bit)

**Comment by mattrummler** [comment]
Oh, just about to go do other things when I realized it might be valuable to mention that when I stop b2fuse.py from running, the folder returns to normal. Therefore we know it is something happening with the folder because of the b2fuse.py & fuse interaction, (seems like it's mostly working... just some piece is missing).

**Comment by falense** [comment]
Are you attempting to mount the folder as root or using sudo? If yes, this
is the wrong way and would cause the symptoms you are describing. Try
mounting the bucket using your regular user account and to a folder that
user has access to.

Best

**Comment by mattrummler** [comment]
Great, thank you very much for clearing up that misunderstanding. 
You are completely correct. 
(I also added my account to the fuse group... it didn't work without this).
I apologize that I missed this in the documentation...
