### ISSUE TITLE
Using rsync to upload files causes my download to increase

### ISSUE THREAD

**Issue by apastuszak** [sondree/b2_fuse#17]
I was trying to test backing up my music library to B2, so I mounted my bucket and kicked off an Rsync of about 12 FLAC albums.  My 1 GB of free downloads got used up in the process.

If I am using rsync to sync files up to b2, how did it used a 1 GB of download bandwidth?

**Comment by falense** [comment]
Rsync can be made to verify each file by hash in order to speed up
transfer/sync. Likely rsync read your data after copying, causing b2fuse to
download your data.

If you just want to push a bunch of files to b2, you might also want to try
the b2 command line tool.

Best

2016-09-15 20:08 GMT+02:00 apastuszak notifications@github.com:

**Comment by apastuszak** [comment]
So, can I use the B2 command line tool to do the upload and then rsync afterwards, or is rsync always going to read all the files and cause me to accrue download charges?

**Comment by falense** [comment]
Unless you turn of the feature to verify files by hashing Rsync will always
result download charges. B2 Command line tool can get around this as it
"knows" that B2 provides hash metadata for stored files, and as such could
sync your files in a similar way to Rsync without using addition download
data. I am not sure whether it currently does this however.

Best

2016-09-15 20:15 GMT+02:00 apastuszak notifications@github.com:

**Comment by ppolewicz** [comment]
b2 command line tool has a `sync` function. It uses file modification date to determine whether the file has changed.

**Comment by apastuszak** [comment]
Where do I find the b2 command line tool?

**Comment by ppolewicz** [comment]
https://github.com/Backblaze/B2_Command_Line_Tool

**Comment by apastuszak** [comment]
Thank you!
