### ISSUE TITLE
Adding tests

### ISSUE THREAD

**Issue by szepeviktor** [sondree/b2_fuse#21]
Hello!

You may steal these tests.
https://github.com/s3ql/s3ql/tree/master/tests

**Comment by falense** [comment]
I have looked at the tests you link. Apart from those operating on a FUSE filesystem itself these are API/Code specific and cannot be "stolen" as you put it. If you would like to add tests to B2Fuse that would be a welcome addition, however I personally will prioritize getting support for B2 Python API stable and releasable (beta-1.3). 

Let me know if you wish to contribute.

**Comment by szepeviktor** [comment]
Thank you for your answer.
