### ISSUE TITLE
Converting b2_fuse into an S3QL backend

### ISSUE THREAD

**Issue by szepeviktor** [sondree/b2_fuse#22]
Please read the comments on https://github.com/Backblaze/B2_Command_Line_Tool/issues/273

S3QL has a lot of features like **tests**, local caching, deduplication, encryption etc.
https://bitbucket.org/nikratio/s3ql/

Please consider adding B2 backend to S3QL
https://bitbucket.org/nikratio/s3ql/issues/181/add-backend-backblaze

**Comment by falense** [comment]
I have looked at adding B2 as a back-end to several libraries before like the S3FS project (https://github.com/s3fs-fuse/s3fs-fuse). My conclusion was that while there would be advantages, B2 has a different feature set and this would not allow me to use B2 to it's full potential without significant code overhead.

In conclusion, if someone wants to take some of the code of B2Fuse and port it to one of these they are free to do so (MIT license), I however will focus the time I have for development on releasing the best possible stand along B2Fuse driver I can.

Best
Sondre

**Comment by szepeviktor** [comment]
Thank you for your answer.
Python is an install-and-debug only language for me.
Maybe I try to implement an S3QL backend.
