### ISSUE TITLE
Add support for installation using PIP

### ISSUE THREAD

**Issue by falense** [sondree/b2_fuse#26]
*TODO*

**Comment by falense** [comment]
Thank you for the contribution @KonstantinSchubert  I ran into a bit of an issue when uploading it to PyPi. Twine reports the following error: 

```
Uploading distributions to https://pypi.python.org/pypi
TypeError: expected string or bytes-like object
```
Google does not produce any relevant results. Any suggestions @KonstantinSchubert ?

**Comment by falense** [comment]
Figure it out. It did not like the wheel type distribution, but the following worked: 

```
python setup.py sdist
twine upload dist/*
```

with the following PyPi config file _~/.pypirc_:

```
[pypi]
username = 
password = 
repository:https://upload.pypi.org/legacy/
```

I will have to work some on the readme and also upload a new more stable version when I resolve #53 though :)

**Comment by KonstantinSchubert** [comment]
@sondree I opened  a PR which updates the readme and fixes the script again, take a look and let me know if it needs improvement.

**Comment by falense** [comment]
Great, thanks! I will have a look as soon as possible

**Comment by falense** [comment]
The new PR was merged. I will go over and make sure nothing broke and try to work on #53 during the weekend (if time permits). Thank you for your contribution!
