### ISSUE TITLE
Alternative temp folder deleted after unmounting!!!

### ISSUE THREAD

**Issue by Fibroblasto** [sondree/b2_fuse#32]
Setting the option "--temp_folder" to an alternative temp folder, after unmounting the filesystem, that temp folder is deleted and all its contents are lost. I have lost a folder with a bunch of good stuff in that way; fuck! fuck! FUCK!!!!!

It happens regardless it is unmounted with "fusermount -u" or with "sudo umount".

Please, correct this ASAP.

**Comment by falense** [comment]
Ouch, I am sorry to hear that. B2Fuse cleans up the temp folder as it's content should only be temporary upon exiting. How would you like it to behave? 

If I may ask, why did you specify a temp folder with content in it? Perhaps the proper way would be for B2Fuse to refuse to use any already existing folder, forcing you to specify a folder that does not yet exist. Then the only way you could lose data would be to copy stuff to the temporary folder while B2Fuse is running.

**Comment by falense** [comment]
Master branch will no just complain and exit should you chose an already existing folder as temp folder. 

Best
Sondre

**Comment by Fibroblasto** [comment]
I thought its default behaviour was to put its stuff in the standard temp folder as other programs do, in /tmp so, I tried with an alternative tmp.

I don't have time to test the enhancement now, but I suppose that with it the issue is closed. Thanks.
