### ISSUE TITLE
Option “--enable_hashfiles” and .sha1 files

### ISSUE THREAD

**Issue by Fibroblasto** [sondree/b2_fuse#34]
In README.md says that “.sha1” files can be disabled by setting variable "enable_hashfiles" to False but:

Setting “--enable_hashfiles false” or “--enable_hashfiles=false” is not accepted. The same for “true”.

It looks that enabling “.sha1” files is already disabled by default and the option “--enable_hashfiles” enables them.

So, if I am right, README.md should be modified accordingly.

Most important: after enabling “.sha1” files with “--enable_hashfiles” if I try to read it with “cat” or copy it to the hard disk the console displays the message “Bad address”. In the case of the copy command it copies a hash file which size is 0, despite the size in the mounted filesystem its size appears to be 42 bytes. If I try to edit a hash file in the mounted filesystem with nano, the console displays the message “Too many open files in system”. In all cases b2fuse.py displays these errors:

> Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 591, in read
    data = create_string_buffer(ret, retsize)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 68, in create_string_buffer
    raise TypeError(init)
TypeError: array('c', '85beca341f971884732121a9083b1253f9ce33e4\n')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 591, in read
    data = create_string_buffer(ret, retsize)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 68, in create_string_buffer
    raise TypeError(init)
TypeError: array('c', '85beca341f971884732121a9083b1253f9ce33e4\n')

If Backblaze question and the article it references to are right this is an important matter:

https://help.backblaze.com/hc/en-us/articles/218020298-Why-does-B2-require-a-SHA-1-hash-to-be-provided-with-an-upload-

https://stackoverflow.com/questions/3830206/can-a-tcp-checksum-produce-a-false-positive-if-yes-how-is-this-dealt-with

**Comment by falense** [comment]
You are correct, readme should be update. What is the full list of parameter you use to produce this bug?

**Comment by Fibroblasto** [comment]
This one, for example:
python b2fuse.py --config_filename config_prueba2_bucket.yaml /mnt/mnt --enable_hashfiles

**Comment by Fibroblasto** [comment]
Python version: 2.7.9

**Comment by Fibroblasto** [comment]
By the way, I can not run the program with python 3. Should I open a new issue about this?

**Comment by falense** [comment]
No. Python 3 is not supported
