### ISSUE TITLE
Random access write not implemented, Borg backup fails with NotImplementedType

### ISSUE THREAD

**Issue by Fibroblasto** [sondree/b2_fuse#41]
I wonder if this issue would be related to issue #38.

I' ve tried to do a test backup using Borg backup stable version (1.0.8): https://borgbackup.readthedocs.io/en/stable/index.html

I've got these errors:

> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 495, in _wrapper
>     return func(*args, **kwargs) or 0
>   File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 604, in write
>     offset, fh)
>   File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 800, in __call__
>     return getattr(self, op)(*args)
>   File "/home/durr/b2/b2_fuse/b2fuse_main.py", line 431, in write
>     self.open_files[path].write(offset, data)
>   File "/home/durr/b2/b2_fuse/filetypes/B2SequentialFileMemory.py", line 72, in write
>     raise NotImplemented()
> TypeError: 'NotImplementedType' object is not callable

The backup failed.

**Comment by falense** [comment]
Try disabling use of disk

**Comment by Fibroblasto** [comment]
I don't know what you mean.

**Comment by dave-fl** [comment]
What makes this call unique that it is not implemented?

**Comment by falense** [comment]
Random writes are more difficult because instead of just appending to a
file, the file has to be extended to a proper size before copying the data
over to b2fuse internal file representation. A write within the file itself
would cause also be a special case as the length of the data block could
exceed the file length.

Ultimately it is a matter of code complexity and performance. It could be
added but is at this time not supported.

On a side note, most programs keep an in memory copy of the data and writes
as a continous sequential block when saving to disk.

**Comment by Fibroblasto** [comment]
> On a side note, most programs keep an in memory copy of the data and writes as a continous sequential block when saving to disk.

Maybe this suggestion is a very big nonsense because of my lack of technical knowledge so, I ask forgiveness if it were the case:

In davfs2 there is a delay in uploading data. It defaults to 10 seconds but it can be modified by the user changing delay_upload in davfs2.conf. I wonder if implementing smething like this would help. Perhaps it would also help with issue #38 whre I reported errors with the command “rm -r” (and also with “cp -r” although I didn't report it).

**Comment by falense** [comment]
I used to have a delay for the "b2fuse local copy" variant. The problem with a delay is consistency, making sure that the online and local structure is in sync. An upload delay would not help this issue in any case, but a more complex implementation of _B2Fuse.filetypes.B2SequentialFileMemory_ would. 

Overall it is not that hard to add, making sure it works correctly and handles every edge case is where it got me when I tried to implement it the last time. 

It is very cool that you guys are using the project and commenting back, perhaps we could make a prioritized wish list of what should be added? I am somewhat limited in what time I can dedicate to the project. Also, if any of you feel comfortable writing some code I am more than happy to accept contributions.

**Comment by Fibroblasto** [comment]
>    I used to have a delay for the "b2fuse local copy" variant. The problem with a delay is consistency, making sure that the online and local structure is in sync.

The problem I see with the lack of sync in delayed writings is that other people connected to the same bucket for colaborative work might open for writing a file that has been already been opened by another user and has not been updated yet. AFAIK, in other cloud services when a file is opened for writing it is locked and nobody else can open it for writing till it is unlocked. I wonder if implementing this (if not yet implemented) would help. Any other potential problems with delayed writings? I am testing Yandex cloud disk which is connected through WebDAV and mounted with davfs2 which implements a 10 seconds writing delay; I would be greatful if you suggested me some way of make it fail because of such delay (yes, I know, I am cruel and eeeeeevil with cloud services).

About priorities, if I were able to reproduce and properly report the fail with “cp -r” and “rm -r” from issue #38 that should be a top priority. If such simple operations fail B2 disk is just unusable.

Please, allow me a rant about all of this: It's Backblaze guys who should be doing this work. It is their business, it is their money. They (hope to) earn money with their service and unless they provide a good way to interact with their cloud disk they won't ever be competitive with other more expensive but better implemented services like the aforementioned Yandex cloud service. Had Backblaze implemented WebDAV or SSH connection they would be unbeatable. Sorry for this rant.

**Comment by falense** [comment]
>  I am testing Yandex cloud disk which is connected through WebDAV and mounted with davfs2 which implements a 10 seconds writing delay; I would be greatful if you suggested me some way of make it fail because of such delay (yes, I know, I am cruel and eeeeeevil with cloud services).

I think this whole discussion has gotten a bit off-topic, however, as it is right now B2Fuse does not actually write to B2 at the same time as you write to B2Fuse. There is actually a delay of sorts. B2Fuse cannot upload the file until you have finished writing to the file. B2Fuse is able to detect when an application is finished with the file as it calls flush or close on the file.

>    About priorities, if I were able to reproduce and properly report the fail with “cp -r” and “rm -r” from issue #38 that should be a top priority. If such simple operations fail B2 disk is just unusable.

Agreed, this should be top. Please add a new issue with all the information you have on the topic.

Note: Sorry about that, accidentally edited you post. I have restored it as it was pushed to me by email.

**Comment by dave-fl** [comment]
Aside from splicing the data array what else needs to be done to fix this? I don't mind taking a look. Just not familiar with fuse or the API.

**Comment by falense** [comment]
That's essentially it. 
This function needs updating to support random writes:

```
def write(self, offset, data):
        if offset == len(self):
            self.data.extend(data)
        else:
             raise NotImplemented()
```

It can be found in _B2SequentialFileMemory.py_, it is possible (but untested) if  _B2FileDisk.py_ under filetypes also need fixing. 

There is a couple of caveats to remember: 

1. A write can start inside of allocated space and end outside (file needs to be extended)
2. A write can start at the end of the file (starting outside currently allocated space)
3. _data_ (to be written) can be of arbitrary length. This is defined by the chunk size written to the filesystem by the user application.

**Comment by falense** [comment]
I stand corrected. I think that the only two cases that needs to be handled is if the file write is inside of the allocated space and at the end. This has been implemented, feel free to prod it and see if it works for you. Random writes has a severe performance penalty for B2Fuse, if you are writing a new application you should try to make it write files sequentially.

**Comment by Fibroblasto** [comment]
Great, great, great! Borg backup works now without errors. It can create, update, prune and delete flawlessly. This was a great improvement. IMO the most basic programs to be used with cloud disks are backup programs and encryptation software. So, be ready to more error reports: I will test encryptation software!

And yes, I have seen the performance penalty. To update a backup where absolutely nothing has changed Borg backup uploads about 400 bytes to the server. But in that process it actually uploaded 5 MB (!!!) and with a speed much less than the one my internet connection allows. It would be great if that could be improved. But I suppose we will have to live with that.

CONGRATULATIONS AND THANKS A LOT!!!

**Comment by dave-fl** [comment]
Just looking at the commit.

Why wouldn't the case where offset+len(data) >= len(self) be handled?  Curious why you would not replace the inner values and append the remaining.

**Comment by dave-fl** [comment]
@Fibroblasto What happens if you update a large file e.g. 10GB file that is mostly sparse.

**Comment by Fibroblasto** [comment]
Even without testing I can tell you: what happens is that… it takes a hell! With mi internet connection speed, to upload a 10 GB file anywhere would take, theoretically, in the very best situation, 26 hours. Unless some chuncks of the file were already in the previous backups and the deduplication feature of the program detected that, in which case only part of the file would be actually uploaded.

Anyway, I don't understand what you mean with a file being sparse.

**Comment by dave-fl** [comment]
Something like VMWare will make files that are marked as sparse.  Basically a file that has the ability to grow to a very large size but only occupies a small amount of disk space.

You can create them like so:

truncate -s 10g test.file

If you run ls -lsh you will see that the file is 10GB but occupies only a single block of space.

**Comment by falense** [comment]
Glad to see it is working :)

I have yet to see a program that writes inside the file ending outside, but
it was a consideration of mine. As it is now, it will return
NotImplemented. It is not particulary hard to add if needed.

B2fuse has a sparse file partial implementation. This complicates the
design but could add two things: ability to start returning data before the
whole file has been downloaded (streaming) and upload of very large files
(large part uploads). Both of these are features are rather complicated to
implement (and no one has been very interested in this yet).

As for the latest part of the discussion, even a marginal change (a single
bit) to a file will require (downloading and) uploading the file again.
This is a limitation in the B2 api.

**Comment by falense** [comment]
A comment on the testing of encryption. B2 cli is, as far as I know,
planning to add encryption as a layer to their python api. This would add
encryption to B2Fuse too.

**Comment by Fibroblasto** [comment]
@dave-fl 

> @Fibroblasto What happens if you update a large file e.g. 10GB file that is mostly sparse.


From Borg documentation: https://borgbackup.readthedocs.io/en/stable/faq.html?highlight=sparse#which-file-types-attributes-etc-are-not-preserved
> ### Which file types, attributes, etc. are not preserved?
> 
> […]
> 
> The precise on-disk (or rather: not-on-disk) representation of the holes in a sparse file. Archive creation has no special support for sparse files, holes are backed up as (deduplicated and compressed) runs of zero bytes. Archive extraction has optional support to extract all-zero chunks as holes in a sparse file.

Therefore, if you don't tell Borg to use compression I suppose it will upload a 10 GB file with an enormous ammount of zeroes inside (I did not test it). But with comprssion enabled, the holes filled with zeroes will be commpressed to a very small space and it will upload quickly (I've tested it).

**Comment by Fibroblasto** [comment]
> A comment on the testing of encryption. B2 cli is, as far as I know, planning to add encryption as a layer to their python api. This would add encryption to B2Fuse too.

I'm not interested in encryptation provided by cloud services in general. My rules about privacy and cloud services are:

1. Cloud providers are not trustworthy in terms of privacy. Never trust them about that.
2. After USA's Patriot Act and Edward Snowden revelations, if the cloud provider is located in USA (e.g. Backblaze) trust it even much less in terms of privacy.
3. If the cloud provider is located in Russia (e,g. Yandex-disk) trust it even less.

Conclusion: do always use independent open-source encryptation tools that you trust.

**Comment by falense** [comment]
When I say that B2 CLI will add support for encryption I am talking about client side encryption. Client side encryption is fundamentally different as you have the one and only key.

**Comment by Fibroblasto** [comment]
And how do I know they don't have a back-door that uploads to them or to the NSA the key? With nowadays laws in USA the police or NSA, (AFAIK even without the control of a judge) can force internet companies to do their best to give them their clients' data and force them to keep silent about that enforcement.

**Comment by falense** [comment]
Two reasons: It is open source https://github.com/Backblaze/B2_Command_Line_Tool and "Client side encryption" (the encryption key is never supposed to leave your computer)

**Comment by Fibroblasto** [comment]
Well, if it is open source and somebody checks carefuly the code to make sure the key never leaves the computer we could trust a little. But let's not forget: in some countries (e.g. USA) the authorities can **force** private compamies to allow them to spy their clients. An e-mail provider intended for privacy decided to close the business because of unbearable pressure from authorities to allow them to sniff arround their clients' emails.

**Comment by falense** [comment]
Closing this issue as discussion have gone off topic and bug appears to be resolved.
