### ISSUE TITLE
question on date on files

### ISSUE THREAD

**Issue by jayhartleyatgithub** [sondree/b2_fuse#42]
I am enjoying using your fuse for b2, but I am having a rather odd issue.   I can mount the filesystem and read and write files.   The folder show the correct timestamp (as it shows directly in the b2 web interface, but the files (non-directories) all have odd dates - various dates sometimes around 1969 other ones show up as July 18 1982.  

Have you seen this before or have any ideas what would cause it?  

I am running ubuntu 16.04 LTS.

Thanks

**Comment by falense** [comment]
That is odd. You are sure that it is not the other way around? Files should get their timestamp based on the upload time from B2, directories cannot be solved in the same way. Can you give me a screenshot from a directory using ´ls -lah´?

**Comment by jayhartleyatgithub** [comment]
Thats for response.   I have attached a screenshot from the mounted drive (mounted on /var/www/data  which shows the date as December 2, 1982.  

I also attached the B2 browser of the same file showing the expected date of 12/19/2016.

![screen shot 2016-12-19 at 1 18 50 pm](https://cloud.githubusercontent.com/assets/7966347/21324083/4e8943f2-c5ee-11e6-9d64-d60fd4dbd867.png)
![screen shot 2016-12-19 at 1 18 39 pm](https://cloud.githubusercontent.com/assets/7966347/21324085/502a55ca-c5ee-11e6-8eb0-109b061f6bff.png)
![screen shot 2016-12-19 at 1 17 21 pm](https://cloud.githubusercontent.com/assets/7966347/21324138/8b948158-c5ee-11e6-82a4-474eaa72f4f0.png)

**Comment by jayhartleyatgithub** [comment]
I enabled debugging, and it appears that the list_file_names function appears to get the date back correctly.   Attached is the debug log results of performing an ls on the file.

![screen shot 2016-12-19 at 1 36 59 pm](https://cloud.githubusercontent.com/assets/7966347/21324617/88243106-c5f0-11e6-9a56-82d496f405be.png)

**Comment by falense** [comment]
Should be fixed now, try it out :)

**Comment by jayhartleyatgithub** [comment]
Perfect!   Thank you so much!
