### ISSUE TITLE
Cannot view contents of bucket

### ISSUE THREAD

**Issue by bensig** [sondree/b2_fuse#46]
I want to store some backups on Backblaze as a disaster recovery option.
I am running the python script in a screen so that it stays mounted. 
I can create directories in there - works great. 

However, when I unmount and remount the b2 storage it appears to be empty. Is this the expected behavior?

**Comment by falense** [comment]
yes. B2 has no concept of directories. Directories only exist locally
until you create a file in the folder.

**Comment by falense** [comment]
I will close this issue now due to inactivity, if you still have questions feel free to open another issue.
