### ISSUE TITLE
Only first 100 files in alphabetical order can be seen

### ISSUE THREAD

**Issue by Volvagia356** [sondree/b2_fuse#53]
#### Issue description
When listing files in a mount, only the first 100 files in alphabetical order are listed. Also, any attempts to upload files with a filename after the first 100 files alphabetically will fail.

#### Steps to reproduce the issue

1. Create and mount an empty bucket
2. Enter the mount and generate 128 files with the following:
```touch `seq -w 1 128` ```
3. Unmount and re-mount the bucket
4. List the files in the bucket with `ls`

#### What's the expected result?

- 128 files from `001` to `128` should be in the directory listing

#### What's the actual result?

- Only files `001` to `100` are in the directory listing. Files `101` to `128` are missing.

**Comment by falense** [comment]
Confirmed, and fixed. Please report back if 1c5e5f4 fixes the issue.

**Comment by Volvagia356** [comment]
It appears to work, but it seems to introduce a new issue where only one file in a directory is listed.

I also discovered two other bugs which seems to be present since at least 1.3 in the process of testing this, which I'll be reporting separately.

**Comment by falense** [comment]
It now lists both more than 100 files in each folder and more than one file in a directory. https://github.com/sondree/b2_fuse/tree/version1.4
