### ISSUE TITLE
Cannot create file or directory with filename that is a suffix of the filename of an existing file

### ISSUE THREAD

**Issue by Volvagia356** [sondree/b2_fuse#54]
#### Issue description
An error occurs if I create a file or directory with a filename that is a suffix of an existing file

#### Steps to reproduce the issue
1. Create a file named "abcd"
2. Create files or directories named "bcd", "cd", and "d"

#### What's the expected result?
- Files "abcd", "bcd", "cd", and "d" are created

#### What's the actual result?
- File "abcd" is created, but creating "bcd", "cd", and "d" fails with the following traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/lib/python2.7/site-packages/fuse.py", line 511, in getattr
    return self.fgetattr(path, buf, None)
  File "/usr/lib/python2.7/site-packages/fuse.py", line 759, in fgetattr
    attrs = self.operations('getattr', self._decode_optional_path(path), fh)
  File "/usr/lib/python2.7/site-packages/fuse.py", line 800, in __call__
    return getattr(self, op)(*args)
  File "/opt/b2_fuse/b2fuse_main.py", line 220, in getattr
    st_size=len(self.open_files[path])
TypeError: __init__() takes at least 3 arguments (1 given)

```

**Comment by falense** [comment]
So I seem to have a partial fix for this issue. It is now possible to create the directories, but files in the directories are not always uploaded.

**Comment by falense** [comment]
90cc4d6 fixes this issue, but it is still affected the problem mentioned in #53. Closing this on to address #53
