### ISSUE TITLE
Cannot remove directory with filename that is a prefix of an existing filename

### ISSUE THREAD

**Issue by Volvagia356** [sondree/b2_fuse#55]
#### Issue description
An error occurs when I try to `rmdir` a directory that has a filename which is a prefix of the filename of an existing file.

#### Steps to reproduce the issue
1. Create file "abcd"
2. Create directories "a", "ab", and "abc"
3. Remove the directories created in step 2

#### What's the expected result?
- Directories are successfully removed

#### What's the actual result?
- Directories fail to be removed with the following traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/lib/python2.7/site-packages/fuse.py", line 533, in rmdir
    return self.operations('rmdir', path.decode(self.encoding))
  File "/usr/lib/python2.7/site-packages/fuse.py", line 800, in __call__
    return getattr(self, op)(*args)
  File "/opt/b2_fuse/b2fuse_main.py", line 320, in rmdir
    self.api.delete_file_version(fileName_to_fileId[path], path)
KeyError: u'abc'
```
Where "abc" is the name of the directory to be removed.

**Comment by falense** [comment]
Directories are a bit of a sticky issue with B2Fuse, as B2 by itself has no concept of directories. A file in B2 may exist in what is more like a number of namespaces. A namespace cannot exist without a file in it. So it is not possible to create an empty directory in B2. To resolve this an make B2Fuse act more like a normal filesystem B2Fuse will fake creating the directories and they will in fact never exist on B2 servers. However, as soon as a file within the directory is created B2Fuse will upload this file to B2 and it will appear as if there are directories. 

I will take a look and see if there is a quick fix for this issue.
