### ISSUE TITLE
tput in start_script

### ISSUE THREAD

**Issue by taw34923904** [sondree/b2_fuse#58]
Hi, 
how usefull is a start_script if you can't script starting with it because it relies on tput which relies on $TERM to be set which can't be set in various starting environments because the system is still starting?

Just pointing out the obvious here.

**Comment by falense** [comment]
Sorry about the very slow response, I have had too much to do lately. 

If this is still an issue for you I suggest you improve the script and issue a pull request. I would be more than happy to accept the contribution.
