### ISSUE TITLE
mountpoint is not empty

### ISSUE THREAD

**Issue by afxgroup** [sondree/b2_fuse#70]
I'm trying to create an automatic backups for my proxmox servers. I've mounted a /mnt/b2 folder and i've assigned it to proxmox so it can use this folder for backups. But when i try to start b2fuse i receive this error:

```
root@node2:/opt/b2_fuse# fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
Traceback (most recent call last):
  File "/usr/local/bin/b2fuse", line 11, in <module>
    load_entry_point('b2fuse', 'console_scripts', 'b2fuse')()
  File "/opt/b2_fuse/b2fuse/b2fuse.py", line 128, in main
    FUSE(filesystem, args.mountpoint, nothreads=True, foreground=True, **args.options)
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 480, in __init__
    raise RuntimeError(err)
RuntimeError: 1
```

But i didn't find any option called nonempty. Where i can find it?

**Comment by falense** [comment]
You never want to mount B2Fuse to a non-empty mountpoint.

**Comment by falense** [comment]
Likely, the application you want to use created one or more files before you were able to mount the bucket. This is possible to resolve by making a the mountpoint not writeable. I do not have the exact permissions required for this is in my head, but a google search should help you.

**Comment by afxgroup** [comment]
mmm.. i've seen that on s3fuse that options exists. And however who prints that error?

**Comment by falense** [comment]
B2Fuse use a library called python fuse. Python fuse prints this error. I
have not exposed an option to override this behavior as I do not see why
you would want or need to, and because there may be unforseen consequences
in doing so.

**Comment by falense** [comment]
If you feel like experimenting, the line to change would be:

```FUSE(filesystem, args.mountpoint, nothreads=True, foreground=True, **args.options)```

to 

``` FUSE(filesystem, args.mountpoint, nothreads=True, foreground=True, nonempty=True, **args.options)```

**Comment by afxgroup** [comment]
It seems to work correctly. You should add a new option that can enable this feature. Basically if i have a dir into the mounted dir i receive that warning but there are no problems

**Comment by falense** [comment]
Added the requested command line option in branch "nonempty". Please check it out if it is still relevant to you: https://github.com/sondree/b2_fuse/tree/nonempty
