### ISSUE TITLE
Error: unauthorized (first run) Everything is installed/configured perfectly

### ISSUE THREAD

**Issue by softwarecreations** [sondree/b2_fuse#73]
Hi, thanks for making & sharing this!

Fresh Ubuntu 18.04 install
* I installed python3-pip fresh
* I followed the python3 setup instructions exactly
* I tried deleting and recreating my key (updated in config.yaml)
* Account ID and bucket ID are definitely correct. I've checked everything at least 5x.
* I also tried running b2fuse with command-line params instead of the config.yaml file and got exactly the same error output.

```
bob@freshpc:/opt/b2_fuse-master$ sudo chown bob:bob -R /opt/b2_fuse-master /home/bob/ /mnt/test-b2/

bob@freshpc:/opt/b2_fuse-master$ python3 -m "b2fuse.tier1_tests"
Hello world Heeeo world Heeeo world
........
----------------------------------------------------------------------
Ran 8 tests in 0.016s

OK

bob@freshpc:/opt/b2_fuse-master$ cat config.yaml
accountId: (12 char lowercase hex code)
applicationKey: K001(another 27 alphanumeric upper and lowercase chars)
bucketId: (24 char lowercase hex code)

#(note that colons and spaces in above file are correct)

bob@freshpc:/opt/b2_fuse-master$ b2fuse /mnt/test-b2
Traceback (most recent call last):
  File "/usr/local/bin/b2fuse", line 11, in <module>
    load_entry_point('b2fuse==1.3', 'console_scripts', 'b2fuse')()
  File "/usr/local/lib/python3.6/dist-packages/b2fuse-1.3-py3.6.egg/b2fuse/b2fuse.py", line 126, in main
  File "/usr/local/lib/python3.6/dist-packages/b2fuse-1.3-py3.6.egg/b2fuse/b2fuse_main.py", line 54, in __init__
  File "/home/bob/.local/lib/python3.6/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/home/bob/.local/lib/python3.6/site-packages/b2/api.py", line 126, in authorize_account
    response = self.raw_api.authorize_account(realm_url, account_id_or_key_id, application_key)
  File "/home/bob/.local/lib/python3.6/site-packages/b2/raw_api.py", line 163, in authorize_account
    return self._post_json(realm_url, 'b2_authorize_account', auth)
  File "/home/bob/.local/lib/python3.6/site-packages/b2/raw_api.py", line 159, in _post_json
    return self.b2_http.post_json_return_json(url, headers, params)
  File "/home/bob/.local/lib/python3.6/site-packages/b2/b2http.py", line 302, in post_json_return_json
    return self.post_content_return_json(url, headers, data, try_count, params)
  File "/home/bob/.local/lib/python3.6/site-packages/b2/b2http.py", line 275, in post_content_return_json
    response = _translate_and_retry(do_post, try_count, post_params)
  File "/home/bob/.local/lib/python3.6/site-packages/b2/b2http.py", line 119, in _translate_and_retry
    return _translate_errors(fcn, post_params)
  File "/home/bob/.local/lib/python3.6/site-packages/b2/b2http.py", line 55, in _translate_errors
    int(error['status']), error['code'], error['message'], post_params
b2.exception.Unauthorized:  (unauthorized)

```
The only unusual thing is I'm trying this on an i386 CPU (not x86_64) but that shouldn't affect anything?

This is what the manual says about Unauthorized:
https://help.servmask.com/knowledgebase/backblaze-b2-error-codes/

```
Code: 401 ‘Unauthorized’
Returned while uploading, indicates the upload URL has expired; A new upload URL can be obtained from b2_get_upload_url or b2_get_upload_part_url
Returned from b2_authorize_account, indicates the account ID is wrong, the account does not have B2 enabled, or the application key is not valid
For all other APIs, there is a problem with the Authorization Token as indicated in the human-readable message. A new Authorization Token can be obtained from b2_authorize_account
```
I only have one backblaze account, which is a b2 account. I normally upload files manually using the b2 cloud web-interface. I got the account code inside the b2 area and created the application key right there also.

When creating the key, it said the expiry is optional, so I left it blank for the first key that I tried. After the first key didn't work, I deleted it and created a new key with expiry of 864000 seconds (10 days). The backblaze said expiry must be in seconds, less than some huge number. I updated the config.yaml with the 2nd key. I tried supplying everything via commandline params for both keys. I got the same error above, even when trying a non-existent key (after deleting the key).

**Comment by dwinss** [comment]
You should use master application token

**Comment by meersjo** [comment]
Using the master application key does indeed work, but is a horrible security practice.

**Comment by metalgeekstl** [comment]
Have the exact same issue. Master app key works but as stated it's bad practice.

**Comment by falense** [comment]
B2Fuse was developed before Backblaze introduced application keys, as such B2Fuse does not support application keys. I have briefly looked into this new feature and it seems to me that it would add a lot of overhead to B2Fuse as it is possible to limit application keys to less than a complete bucket (individual file prefixes). I see the argument about security and I agree, but personally I don't see that adding support to application keys is worth the additional complexity required to support them in B2Fuse. 

That being said, if someone was to implement a prototype and provide a pull request it would likely be accepted ;)

**Comment by falense** [comment]
Project now works with application keys as far as I can tell. I am using it now with a key that is not the master key but has access to all my buckets.
