### ISSUE TITLE
Issues mounting bucket (first run)

### ISSUE THREAD

**Issue by dzaczek** [sondree/b2_fuse#9]
python3 b2fuse.py /home/dzaczek/blaze
  File "b2fuse.py", line 172
    return dict(st_mode=(S_IFDIR | 0777), st_ctime=time(), st_mtime=time(), st_atime=time(), st_nlink=2)
                                                             ^

**Comment by falense** [comment]
Try using python2.7

**Comment by dzaczek** [comment]
Thx for far respond 

```
python 2.7 Traceback (most recent call last):
  File "b2fuse.py", line 499, in <module>
    main(args.mountpoint, args.account_id, args.application_key, args.bucket_id)
  File "b2fuse.py", line 491, in main
    with B2Fuse(account_id, application_key, bucket_id) as filesystem:
  File "b2fuse.py", line 96, in __init__
    account_id = config['accountId']
TypeError: string indices must be integers, not str


```

**Comment by falense** [comment]
There is probably something wrong with you config file. Have you made a "config.yaml" file?

**Comment by dzaczek** [comment]
[Image](http://mycv.var.cat/123.png) image file config.yaml

**Comment by falense** [comment]
You forgot spaces between ":" and <yourvalues>

**Comment by dzaczek** [comment]
[IMG2](http://mycv.var.cat/124.png) is better.

**Comment by falense** [comment]
Well basically it is complaining about formatting of the authentication. Likely this is still caused by a malformed config file.

**Comment by falense** [comment]
Without additional information I am unable to do anything more for this issue.
